import dayjs from "dayjs"

export async function getXRate(from, to, day) {
  if (from === to)
    return {
      message: "success",
      timestamp: "0001-01-01T00:00:00Z",
      from,
      to,
      amount: 1,
      result: 1,
    }
  const today = dayjs()
    .set("hour", 0)
    .set("minute", 0)
    .set("second", 0)
    .set("ms", 0)
  const d = dayjs(day)
  const inThePast = today > d
  const dayArgs = inThePast ? `&day=${d.format("YYYY-MM-DD")}` : ""
  const baseURL = "https://tool.everyday.in.th/xrate?"
  const url = `${baseURL}from=${from}&to=${to}&amount=${1}${dayArgs}`
  try {
    const resp = await fetch(url)
    const json = await resp.json()
    return json
  } catch (error) {
    console.error(error)
    return { message: "failure" }
  }
}

export const CURRENCY_LIST = {
  AED: "United Arab Emirates Dirham (AED)",
  AFN: "Afghanistan Afghani (AFN)",
  ALL: "Albania Lek (ALL)",
  AMD: "Armenia Dram (AMD)",
  ANG: "Netherlands Antilles Guilder (ANG)",
  AOA: "Angola Kwanza (AOA)",
  ARS: "Argentina Peso (ARS)",
  AUD: "Australia Dollar (AUD)",
  AWG: "Aruba Guilder (AWG)",
  AZN: "Azerbaijan Manat (AZN)",
  BAM: "Bosnia and Herzegovina Convertible Mark (BAM)",
  BBD: "Barbados Dollar (BBD)",
  BDT: "Bangladesh Taka (BDT)",
  BGN: "Bulgaria Lev (BGN)",
  BHD: "Bahrain Dinar (BHD)",
  BIF: "Burundi Franc (BIF)",
  BMD: "Bermuda Dollar (BMD)",
  BND: "Brunei Darussalam Dollar (BND)",
  BOB: "Bolivia Bolíviano (BOB)",
  BRL: "Brazil Real (BRL)",
  BSD: "Bahamas Dollar (BSD)",
  BTN: "Bhutan Ngultrum (BTN)",
  BWP: "Botswana Pula (BWP)",
  BYN: "Belarus Ruble (BYN)",
  BZD: "Belize Dollar (BZD)",
  CAD: "Canada Dollar (CAD)",
  CDF: "Congo/Kinshasa Franc (CDF)",
  CHF: "Switzerland Franc (CHF)",
  CLP: "Chile Peso (CLP)",
  CNY: "China Yuan Renminbi (CNY)",
  COP: "Colombia Peso (COP)",
  CRC: "Costa Rica Colon (CRC)",
  CUC: "Cuba Convertible Peso (CUC)",
  CUP: "Cuba Peso (CUP)",
  CVE: "Cape Verde Escudo (CVE)",
  CZK: "Czech Republic Koruna (CZK)",
  DJF: "Djibouti Franc (DJF)",
  DKK: "Denmark Krone (DKK)",
  DOP: "Dominican Republic Peso (DOP)",
  DZD: "Algeria Dinar (DZD)",
  EGP: "Egypt Pound (EGP)",
  ERN: "Eritrea Nakfa (ERN)",
  ETB: "Ethiopia Birr (ETB)",
  EUR: "Euro Member Countries (EUR)",
  FJD: "Fiji Dollar (FJD)",
  FKP: "Falkland Islands (Malvinas) Pound (FKP)",
  GBP: "United Kingdom Pound (GBP)",
  GEL: "Georgia Lari (GEL)",
  GGP: "Guernsey Pound (GGP)",
  GHS: "Ghana Cedi (GHS)",
  GIP: "Gibraltar Pound (GIP)",
  GMD: "Gambia Dalasi (GMD)",
  GNF: "Guinea Franc (GNF)",
  GTQ: "Guatemala Quetzal (GTQ)",
  GYD: "Guyana Dollar (GYD)",
  HKD: "Hong Kong Dollar (HKD)",
  HNL: "Honduras Lempira (HNL)",
  HRK: "Croatia Kuna (HRK)",
  HTG: "Haiti Gourde (HTG)",
  HUF: "Hungary Forint (HUF)",
  IDR: "Indonesia Rupiah (IDR)",
  ILS: "Israel Shekel (ILS)",
  IMP: "Isle of Man Pound (IMP)",
  INR: "India Rupee (INR)",
  IQD: "Iraq Dinar (IQD)",
  IRR: "Iran Rial (IRR)",
  ISK: "Iceland Krona (ISK)",
  JEP: "Jersey Pound (JEP)",
  JMD: "Jamaica Dollar (JMD)",
  JOD: "Jordan Dinar (JOD)",
  JPY: "Japan Yen (JPY)",
  KES: "Kenya Shilling (KES)",
  KGS: "Kyrgyzstan Som (KGS)",
  KHR: "Cambodia Riel (KHR)",
  KMF: "Comorian Franc (KMF)",
  KPW: "Korea (North) Won (KPW)",
  KRW: "Korea (South) Won (KRW)",
  KWD: "Kuwait Dinar (KWD)",
  KYD: "Cayman Islands Dollar (KYD)",
  KZT: "Kazakhstan Tenge (KZT)",
  LAK: "Laos Kip (LAK)",
  LBP: "Lebanon Pound (LBP)",
  LKR: "Sri Lanka Rupee (LKR)",
  LRD: "Liberia Dollar (LRD)",
  LSL: "Lesotho Loti (LSL)",
  LYD: "Libya Dinar (LYD)",
  MAD: "Morocco Dirham (MAD)",
  MDL: "Moldova Leu (MDL)",
  MGA: "Madagascar Ariary (MGA)",
  MKD: "Macedonia Denar (MKD)",
  MMK: "Myanmar (Burma) Kyat (MMK)",
  MNT: "Mongolia Tughrik (MNT)",
  MOP: "Macau Pataca (MOP)",
  MRU: "Mauritania Ouguiya (MRU)",
  MUR: "Mauritius Rupee (MUR)",
  MVR: "Maldives (Maldive Islands) Rufiyaa (MVR)",
  MWK: "Malawi Kwacha (MWK)",
  MXN: "Mexico Peso (MXN)",
  MYR: "Malaysia Ringgit (MYR)",
  MZN: "Mozambique Metical (MZN)",
  NAD: "Namibia Dollar (NAD)",
  NGN: "Nigeria Naira (NGN)",
  NIO: "Nicaragua Cordoba (NIO)",
  NOK: "Norway Krone (NOK)",
  NPR: "Nepal Rupee (NPR)",
  NZD: "New Zealand Dollar (NZD)",
  OMR: "Oman Rial (OMR)",
  PAB: "Panama Balboa (PAB)",
  PEN: "Peru Sol (PEN)",
  PGK: "Papua New Guinea Kina (PGK)",
  PHP: "Philippines Peso (PHP)",
  PKR: "Pakistan Rupee (PKR)",
  PLN: "Poland Zloty (PLN)",
  PYG: "Paraguay Guarani (PYG)",
  QAR: "Qatar Riyal (QAR)",
  RON: "Romania Leu (RON)",
  RSD: "Serbia Dinar (RSD)",
  RUB: "Russia Ruble (RUB)",
  RWF: "Rwanda Franc (RWF)",
  SAR: "Saudi Arabia Riyal (SAR)",
  SBD: "Solomon Islands Dollar (SBD)",
  SCR: "Seychelles Rupee (SCR)",
  SDG: "Sudan Pound (SDG)",
  SEK: "Sweden Krona (SEK)",
  SGD: "Singapore Dollar (SGD)",
  SHP: "Saint Helena Pound (SHP)",
  SLL: "Sierra Leone Leone (SLL)",
  SOS: "Somalia Shilling (SOS)",
  SRD: "Suriname Dollar (SRD)",
  STN: "São Tomé and Príncipe Dobra (STN)",
  SVC: "El Salvador Colon (SVC)",
  SYP: "Syria Pound (SYP)",
  SZL: "eSwatini Lilangeni (SZL)",
  THB: "Thailand Baht (THB)",
  TJS: "Tajikistan Somoni (TJS)",
  TMT: "Turkmenistan Manat (TMT)",
  TND: "Tunisia Dinar (TND)",
  TOP: "Tonga Pa'anga (TOP)",
  TRY: "Turkey Lira (TRY)",
  TTD: "Trinidad and Tobago Dollar (TTD)",
  TVD: "Tuvalu Dollar (TVD)",
  TWD: "Taiwan New Dollar (TWD)",
  TZS: "Tanzania Shilling (TZS)",
  UAH: "Ukraine Hryvnia (UAH)",
  UGX: "Uganda Shilling (UGX)",
  USD: "United States Dollar (USD)",
  UYU: "Uruguay Peso (UYU)",
  UZS: "Uzbekistan Som (UZS)",
  VEF: "Venezuela Bolívar (VEF)",
  VND: "Viet Nam Dong (VND)",
  VUV: "Vanuatu Vatu (VUV)",
  WST: "Samoa Tala (WST)",
  XAF: "Communauté Financière Africaine (BEAC) CFA Franc BEAC (XAF)",
  XCD: "East Caribbean Dollar (XCD)",
  XDR: "International Monetary Fund (IMF) Special Drawing Rights (XDR)",
  XOF: "Communauté Financière Africaine (BCEAO) Franc (XOF)",
  XPF: "Comptoirs Français du Pacifique (CFP) Franc (XPF)",
  YER: "Yemen Rial (YER)",
  ZAR: "South Africa Rand (ZAR)",
  ZMW: "Zambia Kwacha (ZMW)",
  ZWD: "Zimbabwe Dollar (ZWD)",
}
